name: to_do_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.14
  shared_preferences: ^2.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get: ^4.6.5
  collection: ^1.17.1
  shortid: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch
